[package]
name = "todo"
version = "0.1.0"
authors = ["Alex Day <alex@alexday.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
termion = "1.5.5"
